export const ProjectsDB = [
  {
    id: 1,
    name: "iWeather App",
    href: "https://i-weather-app.vercel.app",
    language1: "React",
    color1: "bg-React",
    language2: "Tailwind",
    color2: "bg-Tailwind",
  },
  {
    id: 2,
    name: "Multi Step Form",
    href: "https://multi-step-form-chi-beryl.vercel.app",
    language1: "React",
    color1: "bg-React",
    language2: "Tailwind",
    color2: "bg-Tailwind",
  },
  {
    id: 3,
    name: "News Homepage",
    href: "https://news-homepage-main-indol-psi.vercel.app",
    language1: "React",
    color1: "bg-React",
    language2: "Tailwind",
    color2: "bg-Tailwind",
  },
  {
    id: 4,
    name: "Dice Rolling Game",
    href: "/dice-rolling-game",
    language1: "NextJS",
    color1: "bg-NextJS",
    language2: "Tailwind",
    color2: "bg-Tailwind",
  },
  {
    id: 5,
    name: "Mouse Over Color Animation",
    href: "/mouse-over-color-animation",
    language1: "NextJS",
    color1: "bg-NextJS",
    language2: "Tailwind",
    color2: "bg-Tailwind",
  },
];
